### ISSUE TITLE
Temperature always 0,0

### ISSUE THREAD

**Issue by Krocko** [ebaauw/homebridge-ws#1]
Hello Erik. Thank you, for the great plugin. 
For me the temperature always shows 0,0*C, but the history is correct. Is this a bug, or I am doing something wrong?
![ae22a61d-0e41-4d0a-822a-e7f884477c11](https://user-images.githubusercontent.com/29394115/36114492-74916808-1030-11e8-8be6-6fff71c61412.png)
![33d49f3d-2273-492e-bc9a-4235ee0ed00d](https://user-images.githubusercontent.com/29394115/36114493-74b41164-1030-11e8-9b1f-cb63662e1c98.png)
![022d676b-8402-4a6e-87c3-7ced8d8a8b62](https://user-images.githubusercontent.com/29394115/36114494-74ce0ee8-1030-11e8-89c7-c78dc30ee49f.png)

**Comment by ebaauw** [comment]
Did you try and refresh the screen in Eve (drag down and release)?  Did you try and restart Eve?  Sometimes Eve just loses the connection to homebridge and no longer receives updates.

What temperature does Apple's Home app show?

**Comment by Krocko** [comment]
Yes of course. Apples Home App shows 0*C also. 

![ec659c84-7986-4c0e-a52d-03f45080705b](https://user-images.githubusercontent.com/29394115/36115744-49e6ad62-1034-11e8-99fd-bffb495906bd.png)

**Comment by Krocko** [comment]
I think it is my location. If i set the location to Netherlands/Amsterdam it is working. 

Can you try an set your location to Germany/Erfurt?

**Comment by ebaauw** [comment]
> Can you try an set your location to Germany/Erfurt?

I wasn't planning on moving house...

**EDIT** Sorry, I couldn't resist.

On topic: I think I forgot to change the minValue property of the Current Temperature characteristic for this plugin, so it doesn't display negative temperatures.  See https://github.com/ebaauw/homebridge-hue/issues/30.  Note that they changed HAP-NodeJS since, to force the value into the minValue .. maxValue range, so there's no more error.

**Comment by Krocko** [comment]
> I wasn't planning on moving house...

😜👍🏻

Ok, have changed the values in lib/WSAccessory.js and it is working.

**Comment by ebaauw** [comment]
Solved in v0.0.4 (actually through homebridge-hue-utils@0.4.1).
