### ISSUE TITLE
Translate condition

### ISSUE THREAD

**Issue by Catta1997** [ebaauw/homebridge-ws#10]
Is possible translate the condition on eve app? In Italian is still "clear". It's a "issue" of this plugin or of fakegato?

**Comment by ebaauw** [comment]
HomeKit accessories have no clue about localisation.  The HAP protocol doesn't expose the localisation of the device running the HomeKit app to the accessory.  Accessories report standardised values; it's up to the HomeKit app to localise these.  E.g. temperature is always reported in °C; HomeKit apps translate this to °F.  
Consequently, I will not support localisation in any of my plugins.

The custom _Condition_ characteristic used by Eve holds a text value.  I have no idea if Eve interprets this value, showing it in local language.  Worse, I have no idea where Eve got this characteristic from - it doesn't appear to be defined by Eve themselves and afaik none of the Eve accessories expose it.  
Currently, I simply copy the value received from OpenWeatherMap.  If you can figure out what standard values Eve expects, I'm more than happy to map the OpenWeatherMap values to these.

**Comment by Catta1997** [comment]
In "https://github.com/naofireblade/homebridge-weather-plus" you can translate the condition on Eve App, but this tool does not work correctly

**Comment by ebaauw** [comment]
Looks like they translate the condition server side.  As mentioned before: I'm not going to do that.
