### ISSUE TITLE
Accessories are not being replaced as locations are changed in config

### ISSUE THREAD

**Issue by PedroRA561** [ebaauw/homebridge-ws#14]
Hello, i was trying to figure out the city name that best matches my location and in the meantime i now have a few locations in accessories. In the config file i only have one location. Is there a workaround so i can remove the previous locations ?

**Comment by ebaauw** [comment]
Hm, I thought they would be removed when restarting homebridge?  If not, temporarily remove homebridge-ws from config.json and run `homebridge -R`.

**Comment by nEINSko** [comment]
I cant remove my sensors too. i already deleted plugin in the hope both would go away but they still show up.
also while starting homebridge i get this error:

`Failed to find plugin to handle accessory xxxxx
Failed to find plugin to handle accessory xxxxx`

while xxxx represents my city id and the city name, tried it but while i got -40° on both i wanted to delete both. now they are in my homekit and i cant get rid of them.

And of course, i deleted all homebridge-ws related from config.json.

**Comment by ebaauw** [comment]
Run `homebridge -R` to remove the stale accessories.

**Comment by nEINSko** [comment]
this works for me if i am using putty to connect to homebridge via ssh.

but with the user interface on the web browser, it still shows up.

**Comment by ebaauw** [comment]
Then set `-R` through the settings in web interface.

**Comment by nEINSko** [comment]
okay, somehow after the n-th time of restarting it via the webinterface it worked, they are gone in the interfaces "devices" menu, but they still appeared on the homekit app.

I had to delete the bridge and reinstall it.

Thanks for the Help!

**Comment by ebaauw** [comment]
HomeKit doesn't like configuration changes.  It can take hours to sync them to all your devices over iCloud.
