### ISSUE TITLE
Option to disable logging 

### ISSUE THREAD

**Issue by iwensfortis** [ebaauw/homebridge-ws#18]
Describe the bug

Seams the ws plug-in is logging every update to the log which clutters the log is there an option  to disable the logging of the plug-in?

To Reproduce

Just start plugin every 10 minutes it writes a couple of log lines to the main log.

Expected behavior

An option to only log plugin errors to the main log.

Latest version fresh install 2 days ago.

**Comment by ebaauw** [comment]
Please provide your thoughts how best to implement this to https://github.com/ebaauw/homebridge-lib/issues/26.

**Comment by ebaauw** [comment]
In v2.3.0.  Note that you need to issue multiple _Identify_ requests to change the level of logging.  Please let me know if that works, or if I should expose another characteristic for it.
