### ISSUE TITLE
Leak sensor disable?

### ISSUE THREAD

**Issue by gerarddvb** [ebaauw/homebridge-ws#20]
Is there any way to disable the leak sensor that triggers when its raining?
It is not really accurate in my location and in iOS 14 it will always show in overview.
Disabling is also not possible anymore, because HomeKit sees it as an alarm.

<img src="https://imgur.com/ZJLQoT0.jpg" width="310" height="572"> <img src="https://imgur.com/dDZ0e2n.jpg" width="310" height="672">

**Comment by ebaauw** [comment]
> Is there any way to disable the leak sensor that triggers when its raining?

Currently not.

> in iOS 14 it will always show in overview.

What about the _Notifications_ section in _Home Settings_?

My old iPhone is too old for current iOS versions, so I have no device to test iOS 14 beta on.  I'll wait until the released version of iOS 14, before making any changes to my plugins.  I wouldn't be the first time that Apple removes and re-introduces functionality during the beta cycle.
