### ISSUE TITLE
Any way to disable leak detection?

### ISSUE THREAD

**Issue by beeper99** [ebaauw/homebridge-ws#21]
I love the plug-in, it's simple and just what I need, but the leak detection in HomeKit is freaking my wife out as we live in a rainy place. Is there any way to disable this?

**Comment by ebaauw** [comment]
No.  You can disable the notifications is Home.

**Comment by beeper99** [comment]
> No.  You can disable the notifications in Home.

Thanks!

If you were going to allow this it would be very welcome. I always have a red "leak!" warning in my home app :(
