### ISSUE TITLE
Is there a way to customize the "Leak"-notification?

### ISSUE THREAD

**Issue by h0lz** [ebaauw/homebridge-ws#22]
The term leak ("Leck" in German) for rain isn't that great. 
I would like to customize the pushed phrase.
Is there a way?
 
![IMG_2610](https://user-images.githubusercontent.com/6436979/98450071-c1033f00-2139-11eb-9e6f-af9d49e30fbf.png)

**Comment by ebaauw** [comment]
The notification is a feature of the Home app.  Afaik, it only allows you to customise if and when the notification is sent, but not the message text.

**Comment by h0lz** [comment]
Okay. I'm afraid I supposed so. Is there another notification / characteristic I might look for?
Or is a "rain=yes" notification not intended by HomeKit?

**Comment by ebaauw** [comment]
Home doesn’t support custom characteristics, like _Rain_.   Notifications seem to be supported only for a limited number of security-related sensors.  _Leak_ seems to come closest, at least in my mind.

**Comment by h0lz** [comment]
Ok. Thanks for all your work - especially for this the Homebridge-hue one.  :)
