### ISSUE TITLE
stuck on old weather

### ISSUE THREAD

**Issue by beliy82** [ebaauw/homebridge-ws#23]
hi, it was working perfectly, and about a week ago, its stuck on old weather,
in log file i can see this:

[12/4/2020, 02:15:19] [Weather] warning: npm registry request 1: get /homebridge-ws/latest
[12/4/2020, 02:15:19] [Weather] warning: npm registry request 1: error: registry.npmjs.org: timeout after 5 seconds

**Comment by ebaauw** [comment]
That's just the NPM registry to check for updates of Homebridge WS.

Do you see any errors or warnings contacting the OpenWeatherMap server?

**Comment by beliy82** [comment]
The plugin "homebridge-ws" requires Node version of ^14.15.1 which does not satisfy the current Node version of v12.19.0. You may need to upgrade your installation of Node.

but i got latest node version

**Comment by ebaauw** [comment]
You’re running Homebridge under NodeJS v12.19.0, as per the message.  I develop and test against the latest LTS version of NodeJS, hence the dependency.  Not sure if that’s causing the weather not to be updated, though.

**Comment by ebaauw** [comment]
Actually, the issue seems to be related to the NodeJS version.  For now, either update to NodeJS v14, or downgrade to homebridge-ws@2.4.0.

**Comment by ebaauw** [comment]
Should be fixed in v2.4.2.

**Comment by beliy82** [comment]
Thanks! with the update it was fixed
