### ISSUE TITLE
Too much logs

### ISSUE THREAD

**Issue by apexad** [ebaauw/homebridge-ws#24]
This plugin floods the logs quite a bit and considering it updates every 10min it can hide other important logs.  Anyway you could please add an option to disable the logs or move them to this.log.debug?  If you want me to do a PR I can.

**Comment by ebaauw** [comment]
In Eve, set _Log Level_ to 0 to issue only warning and error messages.

**Comment by apexad** [comment]
I can do this, but why?
Seems like an odd approach to limiting logs is to require the user to download a 3rd party application on their iOS device.
Would it not make much more sense to have it be configurable in the UI via config.schema.json variable?

**Comment by ebaauw** [comment]
No, it wouldn’t, see https://github.com/ebaauw/homebridge-lib/issues/26.

Please complain to Apple that the Home app doesn’t fully support HomeKit, requiring you to use a third party app.

**Comment by apexad** [comment]
I re-downloaded the Eve App and set Log Level to 0. Seems to be working.

I understand the Home app does not support custom characteristics and agree with you that it should.  However, I stand by my thought that there should be a 'global' shut off logs available in the homebridge config ui.  This is how 99% of plugin developers do it.  You could do it as a log level on boot and allow the user to change it after the fact via the custom characteristics or something like that.

Anyway, we are free to disagree and you can close this issue if you want as it's your plugin.
