### ISSUE TITLE
Warning: not using recommended node v14.15.2 LTS. Version is old, current version is newer

### ISSUE THREAD

**Issue by jsiegenthaler** [ebaauw/homebridge-ws#25]
Plugin Reports warning:

[Weather] warning: not using recommended node v14.15.2 LTS

I am using v14.15.3, which is the current LTS version

Can you update the plugin to now warn if the version number is >= the dependency, instead of <> the dependency?

**Comment by ebaauw** [comment]
v2.4.4 lists NodeJS v14.15.4 LTS.
