### ISSUE TITLE
Feature Request: Create an option to disable the leak sensor functionality.

### ISSUE THREAD

**Issue by dppeak** [ebaauw/homebridge-ws#26]
Really want to disable the leak sensor functionality.  We have actual leak sensors in the house and this functionality for weather just creates confusion and worry when it shouldn't. I like the other features of the plugin, but the inability to disable (remove) the "leak" functionality, makes it where I'm going to have to find another plugin for the weather.

Thanks,
Dave

**Comment by luke-rig** [comment]
I second this request. Love having temperature etc. It the leak sensor notifications every time it rains is a bit much

**Comment by ebaauw** [comment]
v2.4.4 introduces the `noLeak` config.json key to prevent updating the _Leak Detected_ characteristic of the _Leak Sensor_.

**Comment by ifeign** [comment]
The leak sensor still appears in the Home app even with this option selected

**Comment by ebaauw** [comment]
Yes?

**Comment by ifeign** [comment]
Is it possible to remove the leak sensor? If it’s disabled, why have it
still visible in the Home app?

**Comment by ebaauw** [comment]
No.  Because all the other characteristics (visible in Eve) are on that service.  It won't trigger when `noLeak` is set.

**Comment by luke-rig** [comment]
Thanks for adding this much better!
