### ISSUE TITLE
Illegal value for Condition Category reported in Homebridge v1.3.0

### ISSUE THREAD

**Issue by jsiegenthaler** [ebaauw/homebridge-ws#28]
Following Warning appears in Homebridge v1.3.0

[20/02/2021, 10:37:26] [homebridge-ws] This plugin generated a warning from the characteristic 'Condition Category': characteristic was supplied illegal value: number 804 exceeded maximum of 255. See https://git.io/JtMGR for more info.

**Comment by ebaauw** [comment]
That doesn't make sense; the characteristic is defined with a `maxValue` of 1000.  Could you please:
- Provide the log message where homebridge-ws announces its version and Homebridge and NodeJS versions;
- Provide the full error message, including the stack trace; and
- Attach `cachedAccessories`.

How long ago did you install Homebridge WS?

**Comment by jsiegenthaler** [comment]
Hi @ebaauw 

I updated Homebridge to v1.3.0 this morning ( a few hours ago).
Here are the log snippets:

[20/02/2021, 11:32:56] [HB Supervisor] OS: Linux 5.4.79-v7l+ arm
[20/02/2021, 11:32:56] [HB Supervisor] Node.js v14.15.5 /usr/bin/node
[20/02/2021, 11:32:56] [HB Supervisor] Homebridge Path: /usr/lib/node_modules/homebridge/bin/homebridge
[20/02/2021, 11:32:56] [HB Supervisor] UI Path: /usr/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[20/02/2021, 11:33:00] [Homebridge UI] Homebridge Config UI X v4.39.0 is listening on :: port 8581
[20/02/2021, 11:33:00] [HB Supervisor] Starting Homebridge with extra flags: -I
[20/02/2021, 11:33:00] [HB Supervisor] Started Homebridge v1.3.0 with PID: 27615
Initializing HAP-NodeJS v0.9.1...

[20/02/2021, 11:33:06] ---
[20/02/2021, 11:33:06] Loaded plugin: homebridge-ws@2.4.7
[20/02/2021, 11:33:06] Registering platform 'homebridge-ws.Lib'
[20/02/2021, 11:33:06] Registering platform 'homebridge-ws.WS'

There is no stack trace for the error message, it is a new warning that appears in Homebridge v1.3.0
Looking for cachedAccessories...

**Comment by jsiegenthaler** [comment]
@ebaauw 
Homebridge WS was installed around a year ago

OK, I found the cachedAccessories file. It's pretty big though:
`-rw-r--r-- 1 homebridge homebridge 375570 Feb 20 11:33 cachedAccessories`

I'm struggling to find a way to transfer the file from my raspberry pi to my windows machine..... I can do a head or a tail on the file and get just the start or the end, would that be enough?

**Comment by jsiegenthaler** [comment]
@ebaauw 
Here's the first 20000 characters of cachedAccessories:

`[{"plugin":"homebridge-ws","platform":"WS","context":{"className":"Forecasts","version":"2.4.7","id":"WS-WINTERTHUR-F","name":"Winterthur Forecast","logLevel":2,"context":{"location":"Winterthur"},"0000003E-0000-1000-8000-0026BB765291":{"name":"Winterthur Forecast","id":"WS-WINTERTHUR-F","manufacturer":"homebridge-ws","model":"OpenWeatherMap","firmware":"1.0"},"00000083-0000-1000-8000-0026BB765291.1d":{"name":"Winterthur Forecast 1d","temperatureUnit":0,"elevation":0,"apparentTemperature":8.1,"clouds":0,"condition":"Clear","conditionCategory":800,"day":"Sunday","dewPoint":0.96,"humidity":50,"observationTime":"Sun Feb 21 2021 12:00:00","pressure":1019,"rain":false,"snow":false,"sunrise":"Sun Feb 21 2021 07:20:19","sunset":"Sun Feb 21 2021 17:57:14","temperature":10.8,"temperatureMin":1,"temperatureMax":12.8,"uvIndex":2.38,"wind":"NNE","windSpeed":4.5,"leak":false,"rain24h":0}},"displayName":"Winterthur Forecast","UUID":"227F8016-2E62-45F0-8794-974EA689B52B","category":1,"services":[{"displayName":"Winterthur Forecast","UUID":"0000003E-0000-1000-8000-0026BB765291","hiddenService":false,"primaryService":false,"characteristics":[{"displayName":"Identify","UUID":"00000014-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":false,"props":{"format":"bool","perms":["pw"]}},{"displayName":"Manufacturer","UUID":"00000020-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":"homebridge-ws","props":{"format":"string","perms":["pr"]}},{"displayName":"Model","UUID":"00000021-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":"OpenWeatherMap","props":{"format":"string","perms":["pr"]}},{"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":"Winterthur Forecast","props":{"format":"string","perms":["pr"]}},{"displayName":"Serial Number","UUID":"00000030-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":"WS-WINTERTHUR-F","props":{"format":"string","perms":["pr"]}},{"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":"1.0","props":{"format":"string","perms":["pr"]}}],"optionalCharacteristics":[{"displayName":"Accessory Flags","UUID":"000000A6-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":0,"props":{"format":"uint32","perms":["pr","ev"]}},{"displayName":"App Matching Identifier","UUID":"000000A4-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":null,"props":{"format":"tlv8","perms":["pr"]}},{"displayName":"Configured Name","UUID":"000000E3-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":"","props":{"format":"string","perms":["pr","pw","ev"]}},{"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":"","props":{"format":"string","perms":["pr"]}},{"displayName":"Hardware Revision","UUID":"00000053-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":"","props":{"format":"string","perms":["pr"]}},{"displayName":"Software Revision","UUID":"00000054-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":"","props":{"format":"string","perms":["pr"]}},{"displayName":"Product Data","UUID":"00000220-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":null,"props":{"format":"data","perms":["pr"]}}]},{"displayName":"Winterthur Forecast 1d","UUID":"00000083-0000-1000-8000-0026BB765291","subtype":"1d","hiddenService":false,"primaryService":false,"characteristics":[{"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":"Winterthur Forecast 1d","props":{"format":"string","perms":["pr"]}},{"displayName":"Leak Detected","UUID":"00000070-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":0,"props":{"format":"uint8","perms":["pr","ev"],"minValue":0,"maxValue":1,"validValues":[0,1]}},{"displayName":"Current Temperature","UUID":"00000011-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":10.8,"props":{"format":"float","perms":["pr","ev"],"unit":"celsius","minValue":-40,"maxValue":100,"minStep":0.1}},{"displayName":"Temperature Display Units","UUID":"00000036-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":0,"props":{"format":"uint8","perms":["pr","pw","ev"],"minValue":0,"maxValue":1,"validValues":[0,1]}},{"displayName":"Current Relative Humidity","UUID":"00000010-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":50,"props":{"format":"float","perms":["pr","ev"],"unit":"percentage","minValue":0,"maxValue":100,"minStep":1}},{"displayName":"Air Pressure","UUID":"E863F10F-079E-48FF-8F27-9C2605A29F52","eventOnlyCharacteristic":false,"value":1019,"props":{"format":"uint16","perms":["pr","ev"],"unit":"hPa","minValue":700,"maxValue":1100,"minStep":1}},{"displayName":"Elevation","UUID":"E863F130-079E-48FF-8F27-9C2605A29F52","eventOnlyCharacteristic":false,"value":0,"props":{"format":"int","perms":["pr","ev","pw"],"unit":"m","minValue":-430,"maxValue":8850,"minStep":10,"adminOnlyAccess":[1]}},{"displayName":"Apparent Temperature","UUID":"00000062-0000-1000-8000-656261617577","eventOnlyCharacteristic":false,"value":8.1,"props":{"format":"float","perms":["pr","ev"],"unit":"celsius","minValue":-40,"maxValue":100,"minStep":0.1}},{"displayName":"Clouds","UUID":"64392FED-1401-4F7A-9ADB-1710DD6E3897","eventOnlyCharacteristic":false,"value":0,"props":{"format":"uint8","perms":["pr","ev"],"unit":"percentage","minValue":0,"maxValue":100,"minStep":1}},{"displayName":"Condition","UUID":"CD65A9AB-85AD-494A-B2BD-2F380084134D","eventOnlyCharacteristic":false,"value":"Clear","props":{"format":"string","perms":["pr","ev"]}},{"displayName":"Condition Category","UUID":"CD65A9AB-85AD-494A-B2BD-2F380084134C","eventOnlyCharacteristic":false,"value":255,"props":{"format":"uint8","perms":["pr","ev"],"minValue":0,"minStep":1}},{"displayName":"Day","UUID":"57F1D4B2-0E7E-4307-95B5-808750E2C1C7","eventOnlyCharacteristic":false,"value":"Sunday","props":{"format":"string","perms":["pr","ev"]}},{"displayName":"Dew Point","UUID":"095C46E2-278E-4E3C-B9E7-364622A0F501","eventOnlyCharacteristic":false,"value":0.96,"props":{"format":"float","perms":["pr","ev"],"unit":"celsius","minValue":-40,"maxValue":100,"minStep":0.1}},{"displayName":"Observation Time","UUID":"234FD9F1-1D33-4128-B622-D052F0C402AF","eventOnlyCharacteristic":false,"value":"Sun Feb 21 2021 12:00:00","props":{"format":"string","perms":["pr","ev"]}},{"displayName":"Rain","UUID":"F14EB1AD-E000-4EF4-A54F-0CF07B2E7BE7","eventOnlyCharacteristic":false,"value":false,"props":{"format":"bool","perms":["pr","ev"]}},{"displayName":"Total Rain","UUID":"CCC04890-565B-4376-B39A-3113341D9E0F","eventOnlyCharacteristic":false,"value":0,"props":{"format":"uint16","perms":["pr","ev"],"unit":"mm","minValue":0,"maxValue":1000,"minStep":1}},{"displayName":"Snow","UUID":"F14EB1AD-E000-4CE6-BD0E-384F9EC4D5DD","eventOnlyCharacteristic":false,"value":false,"props":{"format":"bool","perms":["pr","ev"]}},{"displayName":"Sunrise","UUID":"00000055-0000-1000-8000-656261617577","eventOnlyCharacteristic":false,"value":"Sun Feb 21 2021 07:20:19","props":{"format":"string","perms":["pr","ev"]}},{"displayName":"Sunset","UUID":"00000056-0000-1000-8000-656261617577","eventOnlyCharacteristic":false,"value":"Sun Feb 21 2021 17:57:14","props":{"format":"string","perms":["pr","ev"]}},{"displayName":"Minimum Temperature","UUID":"707B78CA-51AB-4DC9-8630-80A58F07E419","eventOnlyCharacteristic":false,"value":1,"props":{"format":"float","perms":["pr","ev"],"unit":"celsius","minValue":-40,"maxValue":100,"minStep":0.1}},{"displayName":"Maximum Temperature","UUID":"00000064-0000-1000-8000-656261617577","eventOnlyCharacteristic":false,"value":12.8,"props":{"format":"float","perms":["pr","ev"],"unit":"celsius","minValue":-40,"maxValue":100,"minStep":0.1}},{"displayName":"UV Index","UUID":"05BA0FE0-B848-4226-906D-5B64272E05CE","eventOnlyCharacteristic":false,"value":2,"props":{"format":"uint8","perms":["pr","ev"],"minValue":0,"maxValue":10,"minStep":1}},{"displayName":"Wind Direction","UUID":"46F1284C-1912-421B-82F5-EB75008B167E","eventOnlyCharacteristic":false,"value":"NNE","props":{"format":"string","perms":["pr","ev"]}},{"displayName":"Wind Speed","UUID":"49C8AE5A-A3A5-41AB-BF1F-12D5654F9F41","eventOnlyCharacteristic":false,"value":4.5,"props":{"format":"float","perms":["pr","ev"],"unit":"km/h","minValue":0,"maxValue":100,"minStep":0.1}}],"optionalCharacteristics":[{"displayName":"Status Active","UUID":"00000075-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":false,"props":{"format":"bool","perms":["pr","ev"]}},{"displayName":"Status Fault","UUID":"00000077-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":0,"props":{"format":"uint8","perms":["pr","ev"],"minValue":0,"maxValue":1,"validValues":[0,1]}},{"displayName":"Status Tampered","UUID":"0000007A-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":0,"props":{"format":"uint8","perms":["pr","ev"],"minValue":0,"maxValue":1,"validValues":[0,1]}},{"displayName":"Status Low Battery","UUID":"00000079-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":0,"props":{"format":"uint8","perms":["pr","ev"],"minValue":0,"maxValue":1,"validValues":[0,1]}},{"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","eventOnlyCharacteristic":false,"value":"","props":{"format":"string","perms":["pr"]}}]}]},{"plugin":"homebridge-ws","platform":"WS","context":{"className":"WsAccessory","version":"2.4.7","id":"WS-WINTERTHUR","name":"Winterthur","logLevel":2,"context":{"location":"Winterthur","lon":8.75,"lat":47.5},"0000003E-0000-1000-8000-0026BB765291":{"name":"Winterthur","id":"WS-WINTERTHUR","manufacturer":"homebridge-ws","model":"OpenWeatherMap","firmware":"1.0"},"0000008A-0000-1000-8000-0026BB765291":{"name":"Winterthur Temperature","temperatureUnit":0,"temperature":8.5},"00000082-0000-1000-8000-0026BB765291":{"name":"Winterthur Humidity","humidity":76},"E863F00A-079E-48FF-8F27-9C2605A29F52":{"name":"Winterthur Air Pressure","elevation":0,"pressure":1020},"00000083-0000-1000-8000-0026BB765291":{"name":"Winterthur Weather","heartrate":10,"apparentTemperature":6.6,"clouds":86,"condition":"Clouds","conditionCategory":804,"dewPoint":4.51,"observationTime":"Sat Feb 20 2021 11:33:11","rain":false,"snow":false,"sunrise":"Sat Feb 20 2021 07:22:05","sunset":"Sat Feb 20 2021 17:55:41","temperatureMin":2.2,"temperatureMax":13.8,"visibility":10,"uvIndex":2.31,"wind":"North","windSpeed":3.7,"leak":false,"logLevel":2,"rain1h":0,"rain24h":0},"E863F007-079E-48FF-8F27-9C2605A29F52":{"context":{},"history":{"firstEntry":37060,"lastEntry":41092,"history":[{"time":1613362961,"temp":-7.3,"humidity":86,"pressure":1034},{"time":1613363561,"temp":-6.9,"humidity":86,"pressure":1034},{"time":1613364161,"temp":-6.8,"humidity":86,"pressure":1034},{"time":1613364761,"temp":-6.9,"humidity":86,"pressure":1034},{"time":1613365361,"temp":-6.9,"humidity":93,"pressure":1034},{"time":1613365961,"temp":-6.9,"humidity":93,"pressure":1034},{"time":1613366561,"temp":-7.1,"humidity":93,"pressure":1034},{"time":1613367161,"temp":-6.8,"humidity":86,"pressure":1034},{"time":1613367761,"temp":-6.7,"humidity":86,"pressure":1034},{"time":1613368361,"temp":-6.6,"humidity":86,"pressure":1034},{"time":1613368961,"temp":-6.6,"humidity":86,"pressure":1034},{"time":1613369561,"temp":-6.4,"humidity":86,"pressure":1034},{"time":1613370161,"temp":-6.4,"humidity":86,"pressure":1034},{"time":1613370761,"temp":-6.1,"humidity":93,"pressure":1034},{"time":1613371361,"temp":-6.1,"humidity":86,"pressure":1034},{"time":1613371961,"temp":-6.1,"humidity":86,"pressure":1034},{"time":1613372561,"temp":-5.9,"humidity":93,"pressure":1034},{"time":1613373161,"temp":-5.9,"humidity":93,"pressure":1034},{"time":1613373761,"temp":-5.9,"humidity":93,"pressure":1034},{"time":1613374361,"temp":-5.6,"humidity":86,"pressure":1033},{"time":1613374961,"temp":-5.4,"humidity":86,"pressure":1033},{"time":1613375561,"temp":-5.4,"humidity":86,"pressure":1033},{"time":1613376161,"temp":-5.1,"humidity":86,"pressure":1033},{"time":1613376761,"temp":-5.1,"humidity":86,"pressure":1033},{"time":1613377361,"temp":-4.9,"humidity":86,"pressure":1033},{"time":1613377961,"temp":-4.1,"humidity":80,"pressure":1034},{"time":1613378561,"temp":-3.9,"humidity":80,"pressure":1034},{"time":1613379161,"temp":-3.7,"humidity":80,"pressure":1034},{"time":1613379761,"temp":-3.1,"humidity":74,"pressure":1034},{"time":1613380361,"temp":-3,"humidity":74,"pressure":1034},{"time":1613380961,"temp":-2.8,"humidity":74,"pressure":1034},{"time":1613381561,"temp":-2.5,"humidity":74,"pressure":1034},{"time":1613382161,"temp":-2.3,"humidity":74,"pressure":1034},{"time":1613382761,"temp":-2.3,"humidity":74,"pressure":1034},{"time":1613383361,"temp":-2,"humidity":74,"pressure":1034},{"time":1613383961,"temp":-2,"humidity":74,"pressure":1034},{"time":1613384561,"temp":-2,"humidity":74,"pressure":1034},{"time":1613385161,"temp":-1.3,"humidity":69,"pressure":1033},{"time":1613385761,"temp":-0.8,"humidity":69,"pressure":1033},{"time":1613386361,"temp":-1.1,"humidity":69,"pressure":1033},{"time":1613386961,"temp":-0.8,"humidity":69,"pressure":1033},{"time":1613387561,"temp":-0.8,"humidity":69,"pressure":1033},{"time":1613388161,"temp":-0.6,"humidity":69,"pressure":1033},{"time":1613388761,"temp":-0.1,"humidity":69,"pressure":1033},{"time":1613389361,"temp":-0.1,"humidity":69,"pressure":1033},{"time":1613389961,"temp":-0.1,"humidity":69,"pressure":1033},{"time":1613390561,"temp":1.1,"humidity":64,"pressure":1032},{"time":1613391161,"temp":1.1,"humidity":64,"pressure":1032},{"time":1613391761,"temp":1.3,"humidity":64,"pressure":1032},{"time":1613392361,"temp":2.3,"humidity":60,"pressure":1032},{"time":1613392961,"temp":2.3,"humidity":60,"pressure":1032},{"time":1613393561,"temp":1.9,"humidity":60,"pressure":1032},{"time":1613394161,"temp":1.9,"humidity":56,"pressure":1032},{"time":1613394761,"temp":1.9,"humidity":56,"pressure":1032},{"time":1613395361,"temp":1.9,"humidity":56,"pressure":1032},{"time":1613395961,"temp":2.2,"humidity":52,"pressure":1031},{"time":1613396561,"temp":2.2,"humidity":52,"pressure":1031},{"time":1613397161,"temp":2.3,"humidity":52,"pressure":1031},{"time":1613397761,"temp":2.6,"humidity":48,"pressure":1031},{"time":1613398361,"temp":2.4,"humidity":48,"pressure":1031},{"time":1613398961,"temp":2.6,"humidity":48,"pressure":1031},{"time":1613399561,"temp":2.6,"humidity":56,"pressure":1031},{"time":1613400161,"temp":2.6,"humidity":56,"pressure":1031},{"time":1613400761,"temp":2.4,"humidity":56,"pressure":1031},{"time":1613401361,"temp":2.8,"humidity":56,"pressure":1031},{"time":1613401961,"temp":3,"humidity":56,"pressure":1031},{"time":1613402561,"temp":3.2,"humidity":56,"pressure":1031},{"time":1613403161,"temp":3.1,"humidity":56,"pressure":1031},{"time":1613403761,"temp":3.1,"humidity":56,"pressure":1031},{"time":1613404361,"temp":2.9,"humidity":56,"pressure":1031},{"time":1613404961,"temp":2.9,"humidity":65,"pressure":1031},{"time":1613405561,"temp":2.8,"humidity":65,"pressure":1031},{"time":1613406161,"temp":2.6,"humidity":65,"pressure":1031},{"time":1613406761,"temp":2.8,"humidity":60,"pressure":1030},{"time":1613407361,"temp":2.9,"humidity":60,"pressure":1030},{"time":1613407961,"temp":2.9,"humidity":60,"pressure":1030},{"time":1613408561,"temp":2.6,"humidity":64,"pressure":1030},{"time":1613409161,"temp":2.6,"humidity":64,"pressure":1030},{"time":1613409761,"temp":2.7,"humidity":64,"pressure":1030},{"time":1613410361,"temp":2.4,"humidity":64,"pressure":1030},{"time":1613410961,"temp":2.5,"humidity":64,"pressure":1030},{"time":1613411561,"temp":2.6,"humidity":64,"pressure":1030},{"time":1613412161,"temp":3.2,"humidity":69,"pressure":1030},{"time":1613412761,"temp":3,"humidity":69,"pressure":1030},{"time":1613413361,"temp":3,"humidity":69,"pressure":1030},{"time":1613413961,"temp":3.4,"humidity":65,"pressure":1030},{"time":1613414561,"temp":3.5,"humidity":65,"pressure":1030},{"time":1613415161,"temp":3.5,"humidity":65,"pressure":1030},{"time":1613415761,"temp":3.5,"humidity":64,"pressure":1030},{"time":1613416361,"temp":3.5,"humidity":64,"pressure":1030},{"time":1613416961,"temp":3.1,"humidity":64,"pressure":1030},{"time":1613417561,"temp":3.6,"humidity":56,"pressure":1029},{"time":1613418161,"temp":3.9,"humidity":56,"pressure":1029},{"time":1613418761,"temp":3.5,"humidity":56,"pressure":1029},{"time":1613419361,"temp":4.1,"humidity":52,"pressure":1029},{"time":1613419961,"temp":4.3,"humidity":52,"pressure":1029},{"time":1613420561,"temp":4.5,"humidity":52,"pressure":1029},{"time":1613421161,"temp":4.5,"humidity":56,"pressure":1029},{"time":1613421761,"temp":4.8,"humidity":56,"pressure":1029},{"time":1613422361,"temp":4.6,"humidity":56,"pressure":1029},{"time":1613422961,"temp":5.1,"humidity":49,"pressure":1029},{"time":1613423561,"temp":5.1,"humidity":49,"pressure":1029},{"time":1613424161,"temp":4.8,"humidity":49,"pressure":1029},{"time":1613424771,"setRefTime":1},{"time":1613424771,"temp":4.2,"humidity":60,"pressure":1030},{"time":1613425371,"temp":3.9,"humidity":60,"pressure":1030},{"time":1613425971,"temp":3.9,"humidity":60,"pressure":1030},{"time":1613426571,"temp":3.5,"humidity":70,"pressure":1029},{"time":1613427171,"temp":3.5,"humidity":70,"pressure":1029},{"time":1613427771,"temp":3.5,"humidity":70,"pressure":1029},{"time":1613428371,"temp":3.2,"humidity":81,"pressure":1029},{"time":1613428971,"temp":3.2,"humidity":81,"pressure":1029},{"time":1613429571,"temp":3.2,"humidity":81,"pressure":1029},{"time":1613430171,"temp":3.3,"humidity":75,"pressure":1029},{"time":1613430771,"temp":3.3,"humidity":75,"pressure":1029},{"time":1613431371,"temp":3.5,"humidity":75,"pressure":1029},{"time":1613431971,"temp":3.1,"humidity":87,"pressure":1029},{"time":1613432571,"temp":3,"humidity":87,"pressure":1029},{"time":1613433171,"temp":3.2,"humidity":87,"pressure":1029},{"time":1613433771,"temp":3,"humidity":87,"pressure":1029},{"time":1613434371,"temp":3,"humidity":87,"pressure":1029},{"time":1613434971,"temp":3,"humidity":87,"pressure":1029},{"time":1613435571,"temp":3.4,"humidity":75,"pressure":1029},{"time":1613436171,"temp":3.4,"humidity":75,"pressure":1029},{"time":1613436771,"temp":3.2,"humidity":75,"pressure":1029},{"time":1613437371,"temp":3.2,"humidity":81,"pressure":1029},{"time":1613437971,"temp":3.2,"humidity":81,"pressure":1029},{"time":1613438571,"temp":3.2,"humidity":81,"pressure":1029},{"time":1613439171,"temp":3,"humidity":87,"pressure":1028},{"time":1613439771,"temp":3,"humidity":87,"pressure":1028},{"time":1613440371,"temp":3.2,"humidity":87,"pressure":1028},{"time":1613440971,"temp":3.7,"humidity":81,"pressure":1028},{"time":1613441571,"temp":3.6,"humidity":81,"pressure":1028},{"time":1613442171,"temp":3.7,"humidity":81,"pressure":1028},{"time":1613442771,"temp":3.5,"humidity":87,"pressure":1028},{"time":1613443371,"temp":3.8,"humidity":87,"pressure":1028},{"time":1613443971,"temp":3.8,"humidity":87,"pressure":1028},{"time":1613444571,"temp":4,"humidity":81,"pressure":1027},{"time":1613445171,"temp":4,"humidity":81,"pressure":1027},{"time":1613445771,"temp":3.9,"humidity":81,"pressure":1027},{"time":1613446371,"temp":3.9,"humidity":81,"pressure":1027},{"time":1613446971,"temp":4,"humidity":81,"pressure":1027},{"time":1613447571,"temp":3.9,"humidity":81,"pressure":1027},{"time":1613448171,"temp":3.6,"humidity":81,"pressure":1027},{"time":1613448771,"temp":3.6,"humidity":81,"pressure":1027},{"time":1613449371,"temp":3.8,"humidity":81,"pressure":1027},{"time":1613449971,"temp":3.6,"humidity":87,"pressure":1027},{"time":1613450571,"temp":3.8,"humidity":87,"pressure":1027},{"time":1613451171,"temp":4,"humidity":87,"pressure":1027},{"time":1613451771,"temp":3.8,"humidity":81,"pressure":1026},{"time":1613452371,"temp":3.8,"humidity":81,"pressure":1026},{"time":1613452971,"temp":3.7`

I note that I see the following in the file, which corresponds to the warning:

`"conditionCategory":804,`

**Comment by ebaauw** [comment]
Next time, please **attach** the file, do **not** try and list it.  Use `sftp` or similar to copy it from the Pi to Windows, or use the web browser on the Pi to upload/attach the file directly from the Pi.

Luckily the relevant part is listed:
```
{"displayName":"Condition Category","UUID":"CD65A9AB-85AD-494A-B2BD-2F380084134C","eventOnlyCharacteristic":false,"value":255,"props":{"format":"uint8","perms":["pr","ev"],"minValue":0,"minStep":1}}
```
The Condition Category characteristic was created under an old version of Homebridge WS, with the wrong definition (`uint8` instead of `uint16`).  I fixed the definition some time ago already, but the old definition sticks for accessories that are restored from cache.  I'll see if I can "patch" cached characteristics with the latest definition on restore.

**Comment by jsiegenthaler** [comment]
@ebaauw Thanks. Yeah, I struggle to get files from the pi. Haven't found an easy way yet. Sorry.

Would it be simpler for me to simply Remove Single Cached Accessory in Homebridge? 
Or uninstall and then reinstall the homebridge-ws plugin?

**Comment by ebaauw** [comment]
Removing the cached accessory would work.  With Homebridge v1.3.0 you can now disable a plugin (from the UI), so you don't have to go through the un/re-install mess, changing config.json accordingly.

I ran into similar issues with my other plugins, so I'll push the change anyways.  Note that removing the cached accessory will cause HomeKit to treat the re-exposed accessory as a new one, losing any associations to HomeKit rooms, groups, scenes, and automations.  No big deal for Homebridge WS, I suppose, but a pain in the lower back for plugins exposing many accessories, used in automations.

**Comment by jsiegenthaler** [comment]
OK thanks, appreciate the detailed and knowledgeable response. Helps a lot! I'll await your fix.

**Comment by ebaauw** [comment]
I published a new version of homebridge-lib which patches the cached characteristics to the latest definition on restore.  If you re-install Homebridge WS, it should pick up v5.0.8 of homebridge-lib.

**Comment by jsiegenthaler** [comment]
Thanks. I went back to homebridge-ws previous version v2.4.6 and then updated to current v2.4.7
Hopefully that picked up the new homebridge-lib version, the progress was too fast to see if it did....

**Comment by ebaauw** [comment]
A `sudo npm -g list homebridge-lib` should reveal the installed version(s).  Also, Homebridge WS logs its version on startup, incl. the versions of NodeJS, Homebridge, and homebridge-lib.

**Comment by jsiegenthaler** [comment]
Hi Ebaauw/Homebridge-Ws
I ran sudo npm -g list homebridge-lib and it told me:

homebridge-hue@0.12.22 uses homebridge-lib@5.0.6
homebridge-ws@2.4.7 uses homebridge-lib@5.0.8
homebridge-zp@1.1.16 uses homebridge-lib@5.0.5

I see https://github.com/ebaauw/homebridge-lib reports the latest release
is v5.0.7 but the related package.json
<https://github.com/ebaauw/homebridge-lib/blob/master/package.json> reports
5.0.8

Are my apparent multiple versions of homebridge-lib a cause for concern?
Should I make any effort to get hue and zp onto the newest lib version, or
will you handle that in the next update?

**Comment by ebaauw** [comment]
> Are my apparent multiple versions of homebridge-lib a cause for concern?

No.  If you re-install the plugins, they’ll use the latest version.  Otherwise installing the next version (when available) will update homebridge-lib.

Important is that Homebridge WS now has the latest version, and that should solve the issue with _Condition Category_.

**Comment by jsiegenthaler** [comment]
Great thanks
I installed previous versions for ZP and Hue and that updated the
homebridge-lib. All three now report v5.0.8

I think we can close this issue now, thanks a lot for your support.
