### ISSUE TITLE
Wunderground Api Key

### ISSUE THREAD

**Issue by Frank-Friemel** [ebaauw/homebridge-ws#3]
This is a very well developed plugin. I‘ve used WU for my own Weatherstation, but unfortunately WU has terminated the service. Are you going to support a new Api?

**Comment by ebaauw** [comment]
Thanks for the heads-up.  I hadn’t seen this before, but checking my account, I found this: 
https://apicommunity.wunderground.com/weatherapi/topics/end-of-service-for-the-weather-underground-api.
> Your subscriptions, and therefore access, will continue to work through 12/31/2018.

> For developers who use WU API data for non-commercial purposes, you will have access to a new plan for a personal use, low call volume API. Stay tuned for more details as we build this out.

I guess we have to “stay tuned” for a month...

Do you have any suggestions for an alternative API?  It should be easy enough to incorporate that, in place of or in addition to the Wunderground API.

**Comment by Frank-Friemel** [comment]
I always loved WU. I think I am going to wait what the new Api will bring.

 Keep up the good work

**Comment by ebaauw** [comment]
Added support for OpenWeatherMap in v2.1.0.  Note that this version needs changes to `config.json`, delete of `~/.homebridge/accessories/cachedAccessories`,  and a manual rename of the history files, see the [release notes](https://github.com/ebaauw/homebridge-ws/releases).

**Comment by Frank-Friemel** [comment]
Cool, I‘ll sign up for an api key and let you know if your plugin works for me

**Comment by Frank-Friemel** [comment]
Works as promised. And provides a great view with Eve:

![img_0321](https://user-images.githubusercontent.com/747676/51066691-f73e0900-160b-11e9-9e51-b87d7a32aa3d.PNG)

**Comment by ebaauw** [comment]
There some differences in the attributes between Wunderground and OpenWeatherMap, but it seems to work just as well.  Incidentally, my Wundeground key still seems to work.

**Comment by ebaauw** [comment]
> error: Wunderground error: this key is not valid due to exceeding rate plan

Looks like my Wunderground key no longer works.

https://apicommunity.wunderground.com/weatherapi/topics/end-of-feb-wu-api-update:
> On March 4, 2019, all keys not connected to a personal weather station will be turned off.

As far as I can tell, they'll only offer a new free API to PWS uploaders (and then only for the data they provided?).  I don't have a real PWS, so I won't be able to support the new API.
