### ISSUE TITLE
Units wind speed

### ISSUE THREAD

**Issue by redjoto** [ebaauw/homebridge-ws#30]
Any chance to be able to change the units for wind direction from km/h to m/s?

**Comment by ebaauw** [comment]
Hm, OpemWeatherMap actually returns the speed in m/s, and I'm just exposing the value as received from OpenWeatherMap, so the value is in m/s.

**Comment by redjoto** [comment]
Yeah, that’s weird. 50 km/h as seen in picture. If this was m/s I would blow away outside. Can it be something with my API?
![C4D08A0D-D586-4CCD-BD8E-5AF16D479E45](https://user-images.githubusercontent.com/79904766/109650436-80eb2080-7b5d-11eb-9eac-4640fc56f09b.jpeg)

**Comment by ebaauw** [comment]
My bad, I must be looking cross-eyed.  I do (did) multiply the received value by 3.6.  Double-checked that Eve will display m/s with the changed characteristic definition.

**Comment by ebaauw** [comment]
In v2.4.10.

**Comment by redjoto** [comment]
Thank you for such a quick response and fix.
