### ISSUE TITLE
Trouble showing minus degrees in Eve app

### ISSUE THREAD

**Issue by redjoto** [ebaauw/homebridge-ws#31]
Looks like Eve app has problems showing minus degrees in the «At a glance» and «Room» windows. I’m being told to increase the value. Although the graph shows minus degrees.

Is this any known bug?

![C6BA59DF-A180-4C80-81A7-664994E44944](https://user-images.githubusercontent.com/79904766/109926512-531fec00-7cc3-11eb-83c6-8fef94e0b07a.jpeg)
![BD12A19F-69A1-43CB-8792-DA71A7AE03C4](https://user-images.githubusercontent.com/79904766/109926520-54e9af80-7cc3-11eb-9689-a88d72d91180.jpeg)
![D76B02EA-E561-43FB-A89A-8C7544681E03](https://user-images.githubusercontent.com/79904766/109926526-561adc80-7cc3-11eb-8dd5-28d754694131.jpeg)

**Comment by ebaauw** [comment]
What version of Homebridge WS are you on?  What version of Homebridge?

**Comment by redjoto** [comment]
> What version of Homebridge WS are you on? What version of Homebridge?

![46FBD4D0-BA60-45A4-8818-D87D5E07A844](https://user-images.githubusercontent.com/79904766/109927222-26200900-7cc4-11eb-9a9c-e5192f536815.jpeg)
![6F001894-9E74-459C-90C9-026D1B598289](https://user-images.githubusercontent.com/79904766/109927225-27513600-7cc4-11eb-8d8b-69d7fdc1bb20.jpeg)

**Comment by ebaauw** [comment]
Do you see any errors in the Homebridge log?

**Comment by ebaauw** [comment]
Yep, this is a bug alright.  I thought I'd handled the HAP-NodeJS changes correctly, but screwed up.

If you re-install Homebridge WS, it should  pickup the latest homebridge-lib with a fix.

**Comment by redjoto** [comment]
> Yep, this is a bug alright. I thought I'd handled the HAP-NodeJS changes correctly, but screwed up.
> 
> If you re-install Homebridge WS, it should pickup the latest homebridge-lib with a fix.

Thank you, works fine now.
