### ISSUE TITLE
[Feature request] Support for yr.no API

### ISSUE THREAD

**Issue by frodekleven** [ebaauw/homebridge-ws#33]
Adding weather data from Yr would be a great feature, because of the great accuracy of their forecasts, worldwide reach and the fact that their data is free. There is already a Homebridge plugin for Yr, but it uses deprecated XML format forecasts.

Information on their current APIs can be found at https://developer.yr.no

I do understand a bit of JS (used to develop a bit of actionscript nearly 20 years ago, but turned to UX instead), but not nearly enough to actually complete this myself. I do however love to learn new stuff, and would be happy to contribute to making this feature a reality.

A quick intro to YR from their website.
Yr is the joint online weather service from the Norwegian Meteorological Institute (met.no) and the Norwegian Broadcasting Corporation (NRK). These two public institutions have worked together since 1923 transmitting weather forecasts to Norway and abroad.

Yr is unique in Europe because of our very detailed weather forecasts and our free data policy. Information about the free weather data service.

Yr offers weather forecasts in English (in additon to Norwegian Nynorsk and Norwegian Bokmål) for around 1 million places in Norway and 12 million places worldwide.

**Comment by ebaauw** [comment]
That looks to be a completely different API from OpenWeatherMap, with different attributes, and different forecast periods.  It will be easier (and less work) to create a new plugin for this, than to adapt Homebridge WS to work with both APIs.

**Comment by frodekleven** [comment]
Thanks for having a look at it. Guess that means I will have to try to figure out how to write a plugin, then.
