### ISSUE TITLE
Separate temperature sensors for high and low temperature of the day

### ISSUE THREAD

**Issue by CooperCGN** [ebaauw/homebridge-ws#35]
Would it be possible to have an option for separate temperature sensors for the daily high and low?

Background is I am using mostly “converted to shortcuts” automations, some of them rather complex and when selecting the weather device it results in showing the different options as some kind of generic device without the corresponding name available like shown in the following picture.

![DB915C20-F8B2-4485-B155-22BE4D553198](https://user-images.githubusercontent.com/29116509/117586600-729b2100-b119-11eb-9741-5ca9d5f90a64.jpeg)

**Comment by ebaauw** [comment]
Apple’s Home app doesn’t support all of HomeKit, but you can create automations on these in Eve or Home+.  I don’t know Shortcuts weel enough, but I’d imagine it’s just as broken as Home.

Creating separate temperature sensors for min and max temperature would require a new accessory for these, or it will break the Eve history.  While technically possible, it’s beyond the scope of Homebridge WS.

**Comment by CooperCGN** [comment]
Of course I know about the possibilities of creating automations with the eve or home+ apps. Still they won’t allow for multistep automations with multiple conditions and if then else structures which makes them way more powerful than the regular automations. It’s just a mess that the home/shortcut app shows all the custom characteristics as just “custom” and not with the given names. So each time one has to count from the top or bottom of the list. That’s why I thought of the additional temperature sensors as the current temperature is already showing up as separate accessory.

I can understand though it’s too much of a hassle.

![E8CC4B84-90DB-4F76-87A8-30B4D4DFC40B](https://user-images.githubusercontent.com/29116509/117654340-e844d280-b195-11eb-860e-4d76a682f918.jpeg)
