### ISSUE TITLE
Error upgrading

### ISSUE THREAD

**Issue by tojorocha** [ebaauw/homebridge-ws#39]
![B8694357-7C09-431B-848F-7CCD1CEE2BA8](https://user-images.githubusercontent.com/63009635/140589975-ddc96fbb-14f8-4994-b41c-108cc1facf73.jpeg)

**Comment by ebaauw** [comment]
I think this is an error with an old version of `npm` that fails under NodeJS v16.  Can you (re-)install `npm` or does that show a similar error?  I’m afraid the workaround is to downgrade NodeJS, update `npm`, update NodeJS.  See https://github.com/homebridge/homebridge/issues/3002#issuecomment-955994607.

**Comment by tojorocha** [comment]
Solved. Thanks a lot
