### ISSUE TITLE
City ​​with umlauts

### ISSUE THREAD

**Issue by niwre2019** [ebaauw/homebridge-ws#4]
Hello,

the plugin works very well, unfortunately I get a mistake in cities with umlauts like „München“ or „Nürnberg“.  How do I get the correct values ​​here?

Thank you.

**Comment by ebaauw** [comment]
homebridge-ws does nothing with the city names, except pass them on to OpenWeatherMap.  It seems like they only support regular English letters.  `"Muenchen"` seems to works, as well as the English `"Munich"`.  In HomeKit, you can change the name of the accessory and services back to `München`.

**Comment by niwre2019** [comment]
Many thanks for your help.  I would have tried it with „Muenchen“ and „Nuernberg“, unfortunately that did not work for me.  I'll try the English name.
