### ISSUE TITLE
Probability of rain

### ISSUE THREAD

**Issue by sercontri** [ebaauw/homebridge-ws#40]
Hi, congratulations on the great job.  I wanted to know if there would be an option in future updates to include the percentage of probability of rain in HomeKit, thanks.

**Comment by ebaauw** [comment]
Technically, it would be possible.  in fact, Homebridge WS used to show this when sourcing the forecast from Wunderground.  Unfortunetely IBM discontinued their free service when they acquired Wonderground, and OpenWeatherMap doesn't provide rain probability.
