### ISSUE TITLE
Plugin showing 0ºC

### ISSUE THREAD

**Issue by FranciRoosters** [ebaauw/homebridge-ws#43]
Hello, today I had to reinstall the plugin due to a power outage and when I did and re-enabled all my related automations, it showed 0 degrees Celsius on my Home app homepage. It still does. Do I have to wait for the API key to do its work? Why can’t I see the correct number of degrees? Thank you.

**Comment by ebaauw** [comment]
Please attach a debug log file, see https://github.com/ebaauw/homebridge-hue/wiki/FAQ#homebridge

**Comment by FranciRoosters** [comment]
![Uploading 62C0E4ED-AE41-4691-BB50-837A3AC3FFD0.png…]()

**Comment by FranciRoosters** [comment]
USER: pi
DIR: /usr/local
CMD: sudo
-E
-n pm install
-g @switchb
ot/homebridge-switchbot@latest
pm WARN EBADENGINE Unsupported engine
{
pm WARN EBADENGINE
package:
"@switch
bot/homebridge-switchbot@1.3.0
pm WARN EBADENGINE
required:
{ homeb
ridge:
^1.3.8'
, node:
'^14.18.1
^16
. 13.0
}
pm WARN EBADENGINE
current: { node:
'V14.16.0
npm:
nom WARN EBADENGINE
'7.6.3'

Don’t mind the plugin name. I get the same error with yours.

**Comment by ebaauw** [comment]
EBADENGINE is a warning by `npm` that you're running a version of NodeJS (v14.16.0, by the looks of it), that's not supported by the package you're installing.  It's just a warning, though, the package would still install.  Why aren't you using the latest LTS version (v16.13.1) of NodeJS?

**Comment by FranciRoosters** [comment]
Honestly, because it’s confusing. First off, I run HB on Raspbian (Raspberry PI 4) but I own Macs, so I’m not sure which command to run going by HB’s dev. See here: https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js
Additionally, I’m afraid to lose part of of my HB setup. The HomeBridge dev himself says that’s “not a risk-free exercise”. 
And finally, anytime I’ve restarted my Raspberry server, my HomeKit setup would go to a previous state without some plugins I have installed later. And if I understood correctly, restarting the server after a new node is required. 

Now, if you tell me that the plugins will still work even if I don’t necessarily update the node, I’ll think about think when .14 will stop receiving support before April 2023. 

Thank you for your support.

**Comment by ebaauw** [comment]
> And finally, anytime I’ve restarted my Raspberry server, my HomeKit setup would go to a previous state without some plugins I have installed later

That sounds like a broken (worn out) µSD card.  Somehow it switches to read-only mode (to protect your data?), but Raspberry Pi OS happily continues to write to the file system cache, giving you no clue that something is really badly wrong, until you reboot (and the cache is lost).

**Comment by FranciRoosters** [comment]
I installed Node.JS to the latest version. Everything went surprisingly smoothly. No resetting HomeKit devices or automations whatsoever. Phew!

Thank you for your support. 🙂
