### ISSUE TITLE
home asssitant integration port to homebridge

### ISSUE THREAD

**Issue by Jogistar** [ebaauw/homebridge-ws#45]
Hi @ebaauw 
I dont know if this is the correct forum to reach out to you, but here goes nothing :)

Im looking for some help porting a home assistant plugin to homebridge. 
This one:
https://www.home-assistant.io/integrations/ondilo_ico/
I´t looks like ondilo supports an API for integration

I think it´s to big a job for me, because I haven´t learned to code, but I would like to help the best way I can.
Would you be interested in this project?

I would of course sponsor you on this work :)

Kind regards
Joachim

**Comment by ebaauw** [comment]
I’m not interested in developing plugins for devices I don’t use myself.  Best ask on Discord in the **#plugin-bounties** channel.
