### ISSUE TITLE
Option for new API 'One Call 3.0'

### ISSUE THREAD

**Issue by CENGOiSM** [ebaauw/homebridge-ws#47]
Due to their new API 3.0, every API key (or account) created since 08.2022 can only access the new /data/3.0/ endpoint. Existing keys should work for the moment.

Maybe the default behavior should implement the new 3.0 api and expose an configuration for the legacy api 1.0 or vice versa.

**Comment by ebaauw** [comment]
See also the discussion on Discord.

What API key did you create, the "One Call by Call" subscription plan or the Free plan (from the Professional collections)?  I understand you need to provide billing info for the "One Call by Call" subscription plan (even though you get 1000 calls per day for free)?  
I think I'd rather revert to `weather` and `forecast` endpoints under the Free plan than "upgrade" to the 3.0 `onecall` endpoint.  Both endpoints seem to report the same info (although structured a bit differently).

I have a free plan, for years already.  The 2.5 `onecall` still works for me; the 3.0 `onecall` returns a 401, as documented, see below.

Could you please double-check whether a newly created API key under the Free plan still works with the 2.5 `onecall` endpoint?

Could you please double-check whether an API key under the "One Call by Call" subscription plan works with the `weather` endpoint?  Homebridge WS uses this to map the city name to the lat/lon coordinates.  Afaik, the `onecall` endpoint doesn't provide any means to specify a city name.

Here's the responses using my API key:
```
$ curl -s -H "Content-Type: application/json" "https://api.openweathermap.org/data/2.5/weather?appid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&units=metric&q=Amsterdam" | json
{
  "coord": {
    "lon": 4.8897,
    "lat": 52.374
  },
  "weather": [
    {
      "id": 801,
      "main": "Clouds",
      "description": "few clouds",
      "icon": "02d"
    }
  ],
  "base": "stations",
  "main": {
    "temp": 15.06,
    "feels_like": 15.02,
    "temp_min": 13.82,
    "temp_max": 15.51,
    "pressure": 1004,
    "humidity": 92
  },
  "visibility": 10000,
  "wind": {
    "speed": 5.66,
    "deg": 150
  },
  "clouds": {
    "all": 20
  },
  "dt": 1662705969,
  "sys": {
    "type": 2,
    "id": 2005807,
    "country": "NL",
    "sunrise": 1662699879,
    "sunset": 1662747085
  },
  "timezone": 7200,
  "id": 2759794,
  "name": "Amsterdam",
  "cod": 200
}
```
```
$ curl -s -H "Content-Type: application/json" "https://api.openweathermap.org/data/2.5/onecall?appid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&units=metric&lon=4.8897&lat=52.374&exclude=minutely,hourly,daily" | json
{
  "lat": 52.374,
  "lon": 4.8897,
  "timezone": "Europe/Amsterdam",
  "timezone_offset": 7200,
  "current": {
    "dt": 1662707392,
    "sunrise": 1662699879,
    "sunset": 1662747085,
    "temp": 15.64,
    "feels_like": 15.61,
    "pressure": 1004,
    "humidity": 90,
    "dew_point": 14.01,
    "uvi": 0.23,
    "clouds": 75,
    "visibility": 10000,
    "wind_speed": 6.69,
    "wind_deg": 160,
    "weather": [
      {
        "id": 803,
        "main": "Clouds",
        "description": "broken clouds",
        "icon": "04d"
      }
    ]
  }
}
```
```
$ curl -s -H "Content-Type: application/json" "https://api.openweathermap.org/data/3.0/onecall?appid=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&units=metric&lon=4.8897&lat=52.374&exclude=minutely,hourly,daily" | json
{
  "cod": 401,
  "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."
}
```

**Comment by ebaauw** [comment]
Could you please try beta v2.5.25-0?  It should default to `onecall` 3.0, assuming a new API key from the "One Call per Call" subscription plan, but falls back to 2.5 to support old API keys from the Free plan.

**Comment by gNeeUs** [comment]
Perhaps the below can help with troubleshooting Erik, it is the result of a clean installation of your homebridge-ws v2.5.24 with OpenWeather API key obtained today under the traditional Free program (thus not the One Call API 3.0). While Homebridge starts up and all my other plugins work successfully, this weather plugin does not seem to run correctly, and on my iPhone Home app it only shows a "Climate 0.00" button.

I kindly also refer to similar issues (but worse) with apparently new installations of a similar plugin https://github.com/naofireblade/homebridge-weather-plus/issues/244.

Here goes my log:

[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast: set Serial Number to "WS-XXX-F"
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast: set Manufacturer to "homebridge-ws"
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast: set Model to "OpenWeatherMap"
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast: set Firmware Revision to "1.0"
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast 1d: set Temperature Display Units to 0
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast 1d: set Elevation to 0 m
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy [#######]: ##.###°N, ##.####°W
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast: set Serial Number to "WS-XXX-F"
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast: set Manufacturer to "homebridge-ws"
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast: set Model to "OpenWeatherMap"
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast: set Firmware Revision to "1.0"
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast 1d: set Temperature Display Units to 0
[9/13/2022, 5:02:06 PM] [Weather] mycityinfo_obfuscated_for_privacy Forecast 1d: set Elevation to 0 m
[9/13/2022, 5:02:08 PM] [Weather] openweathermap request 1: GET onecall?lat=##.###&lon=-##.####&exclude=minutely
**[9/13/2022, 5:02:08 PM] [Weather] warning: openweathermap request 1: http status 401 Unauthorized**
[9/13/2022, 5:02:08 PM] [Weather] openweathermap request 2: GET onecall?lat=##.###&lon=-##.####&exclude=minutely
**[9/13/2022, 5:02:08 PM] [Weather] warning: openweathermap request 2: http status 401 Unauthorized**

I will be trying the beta 2.5.25-0 next, and report back with my findings.

**Comment by gNeeUs** [comment]
> I will be trying the beta 2.5.25-0 next, and report back with my findings.

On second thought, perhaps not yet... I don't know how to install such beta unless it is packaged or available in Homebridge UI. If you wish to send some instructions I can follow, I'd be happy to try it out and report on my findings. I'm keen to resolve this so I don't have to go experiment with other weather plugins which are bound to also fail if there is indeed an issue with support for new API formats. Thanks!

**Comment by gNeeUs** [comment]
I used the Install Alternative Version and managed to install the beta. Logs now show the following:

[9/14/2022, 11:23:04 AM] [Weather] openweathermap request 4: GET 2.5/onecall?lat=##.####&lon=-##.#&exclude=minutely
[9/14/2022, 11:23:04 AM] [Weather] warning: openweathermap request 4: openweathermap status: 401 Invalid API key. Please see http://openweathermap.org/faq#error401 for more info.

Hope this experiment helps in finding a solution. Thanks!

**Comment by ebaauw** [comment]
API keys under the One Call per Call plan should now work with the beta, which defaults to `onecall` 3.0.  Existing older API keys under the Free plan (still?) allow `onecall` 2.5, and still work with the beta, as it falls back to `onecall` 2.5 when `onecall` 3.0 is denied.  Newly/recently generated API keys on the Free plan won’t work, as they allow neither `onecall` 3.0 nor 2.5.

To support newly generated Free-plan keys, Homebridge WS would need to revert to calling `weather` and `forecast` instead of `onecall`.  This would need more serious code changes.  Not only do these calls format the result differently, there’s also fewer forecasts (3-hourly for 5 days instead of hourly for 48 hours and daily for 8 days).

**Comment by ebaauw** [comment]
In v2.5.25.

**Comment by gNeeUs** [comment]
I caved in anyway and upgraded my openweathermap key to One Call API 3.0 format, and all is working fine now. Progress :-) 

Thank you for your time and dedication online!
