### ISSUE TITLE
All Forecast Sensors have the same name

### ISSUE THREAD

**Issue by benzman81** [ebaauw/homebridge-ws#48]
Hi, I have the Problem, that all forecast sensors have the same name "MyCity Forecast". Since a have forecast of 12 hours and additional two days I get 14 sensors with this name. I use iOS 16 on iPhone XS Max.

**Comment by ebaauw** [comment]
Probably an iOS 16 "feature": it shows the accessory name instead of the service name.  Note that all forecasts are exposed on a single accessory, with a service per forecast.

**Comment by benzman81** [comment]
Maybe we now need multiple accessories as this is now not usable. Looking at the sensors I can at least see the date/time in eve app of what forecast the sensor is for, but when I want to create an automation I do not see which sensor is which.

**Comment by benzman81** [comment]
https://github.com/homebridge/homebridge/issues/3210

**Comment by ebaauw** [comment]
So it’s an iOS bug.  Before changing anything in Homebridge WS, beter wait a couple of iOS versions to see if Apple fixes this.  Meanwhile, you can change the names from HomeKit.

Exposing each forecast as a separate accessory is probably a bad idea: you’re bound to run into HomeKit limits.

**Comment by benzman81** [comment]
Sounds reasonable.
