### ISSUE TITLE
Missing config.schema.json

### ISSUE THREAD

**Issue by cbrandlehner** [ebaauw/homebridge-ws#5]
According to the [documentation ](https://github.com/homebridge/Documentation/blob/master/Schema.md) there should be a config.schema.json file.
Using this file also helps users to configure the settings using a browser when using [Config UI X](https://github.com/oznu/homebridge-config-ui-x)

**Comment by ebaauw** [comment]
> According to the documentation there should be a config.schema.json file.

The link to the documentation is for plugins being managed by the @homebridge GitHub account.  They created this account quite some time ago, but then went silent.  It doesn't look like any plugins have been moved over there.

> Using this file also helps users to configure the settings using a browser when using Config UI X

Also?  What else does it do?

I have tried homebridge-config-ui-x in the past, but I'm not currently running that plugin.  I run homebridge as a service under user `pi` from `systemctl` and I've installed homebridge and the plugins using `sudo npm -g`.  homebridge-config-ui-x will only manage this setup when `sudo` is enabled.  I'm no fan of web sites being able to run privileged commands.  Using a non-standard homebridge installation so homebridge-config-ui-x can run without `sudo` is bound to lead to more issues than it prevents.

I'm a big fan of anything that will reduce the number of config.json related issues, and would consider creating a `config.schema.json` for all my plugins, not just for homebridge-ws.  I'm not sure I've seen any `config.schema.json` before.  Do you know of any other plugins that actually provide this?  I dislike their lack of support for user-defined keys, which I currently use for homebridge-hue.  Their workaround of using an array won't guarentee uniqueness of the key.

**Comment by ebaauw** [comment]
Hm, I re-installed homebridge-config-ui-x on my test machine and added the `config.scheme.json` to the homebridge-ws installation.  I'm now seeing a _Settings_ option for homebridge-ws, but I cannot seem to add any locations.

**Comment by cbrandlehner** [comment]
The file might not be perfect, I had problems adding multiple locations to that array too. However I did not really test this as thought that configurating more than one location for one weather station is a contradiction anyhow.

**Comment by cbrandlehner** [comment]
Other plugins using jonfig.schema.json:
https://github.com/merdok/homebridge-webos-tv
https://github.com/itsmepetrov/homebridge-zigbee

**Comment by ebaauw** [comment]
>  more than one location for one weather station is a contradiction anyhow.

The plugin creates a separate virtual weather station for each location.

**Comment by ebaauw** [comment]
Added schemas for homebridge-ws and homebridge-zp.  It's way more powerful than the documentation suggests.  Created an issue, https://github.com/oznu/homebridge-config-ui-x/issues/289, for the inability to add elements to the array.
**EDIT**: fixed in homebridge-config-ui-x v4.4.0

**Comment by cbrandlehner** [comment]
Excellent, thank you very much.

**Comment by cbrandlehner** [comment]
closing
