### ISSUE TITLE
homebridge ws

### ISSUE THREAD

**Issue by marco-hue** [ebaauw/homebridge-ws#50]
from version 2.7 the "water loss sensor" is no longer available when it starts to rain, is it possible to restore it? it is very important to me thank you

**Comment by ebaauw** [comment]
It’s now a motion sensor, so you can still get notifications, but they’re no longer presented as alarms.

**Comment by marco-hue** [comment]
yes I noticed, but I would need a real alarm, to warn especially at night, thank youInviato da Marco Il giorno 20 mar 2023, alle ore 01:56, Erik Baauw ***@***.***> ha scritto:﻿
It’s now a motion sensor, so you can still get notifications, but they’re no longer presented as alarms.

**Comment by ebaauw** [comment]
In v2.7.8.

When you need to set `leakSensor` in `config.json`, each location accessory get an additional _Leak Sensor_.
