### ISSUE TITLE
Free subscriptions to OpenWeatherMap will no longer work

### ISSUE THREAD

**Issue by ebaauw** [ebaauw/homebridge-ws#52]
OpenWeatherMap will discontinue the OneCall v2.5 API this June, see https://openweathermap.org/one-call-transfer.

By default, Homebridge WS already uses the OneCall v3.0 API.  This API version requires a "One Call by Call" subscription with OpenWeatherMap.

For people still using an old "Free" subscription, Homebridge WS falls back to OneCall v2.5.  This fallback will no longer be possible, once OpenWeatherMap discontinues v2.5.

**Comment by Vampier** [comment]
I suggest they better rename to CloseWeatherMap - thanks for creating this plugin. Too bad it got 50%  MyQ-ed :(

**Comment by dcompane** [comment]
I would like to change the cycle time from 10 mins (default) to 5 minutes, but I do not see a way, other than inspecting the code. Am I missing something? The use case is to be more granular when turning on/off the fans and AC, based on weather data. Thoughts? I can open a separate feature request if you think it is needed. Thanks for your effort in maintaining this plugin in!

**Comment by ebaauw** [comment]
Please do not hijack issues.  Use Discord for questions, or open a new issue.

**Comment by ebaauw** [comment]
It's now August, but my key from the pre-OneCall API free plan still works with OneCall 2.5.
```
Aug 14 09:52:22 pi4 hb-service.js[911683]: [Weather] openweathermap request 72: GET 2.5/onecall?lat=52.***&lon=4.***&exclude=minutely
Aug 14 09:52:22 pi4 hb-service.js[911683]: [Weather] openweathermap request 72: 200 OK
```
(masked the detailed geolocation).

**Comment by ebaauw** [comment]
Looks like OneCall 2.5 has been discontinued and the free plan no longer works.  v2.7.27 removes OneCall 2.5 support and only uses OneCall 3.0.
