### ISSUE TITLE
Maximum Temperature 

### ISSUE THREAD

**Issue by PNWOregon** [ebaauw/homebridge-ws#54]
Hi, the plugin has been awesome since I started using it over a year ago but as of recent the maximum temperature has stopped woeking. Not sure what happened as everything else is functioning normally. If I check the logs I can see all the other data points including the minimum temperature. I currently have not update to API 3.0 but I’m not sure if that would effect my access to that data today or not.

thanks for the awesome plugin!

**Comment by ebaauw** [comment]
I'm still using the free subscription with OneCall 2.5, and Maximum Temperature gets updated regularly.  Maybe OpenWeatherMap does no longer include it for your location?  Set _Log Level_ to 2, to see the API response from OpenWeatherMap.

**Comment by PNWOregon** [comment]
I’m not quite sure how to turn on level to log within Homebridge. I did turn on debugging mode, but that didn’t give me much more other than “exclude hourly” and a few other little details that don’t seem to be effecting max temperature.

**Comment by ebaauw** [comment]
You set it on the _Weather_ service in HomeKit, using Eve or another decent HomeKit app.

**Comment by PNWOregon** [comment]
So the good news is without Intervention on my end, it seems to have had resolved itself this morning and maximum temperature has reappeared. That being said, I still wanted to better understand how to utilize the log levels in the future to solve problems. I was able to locate log level within the Eve app, but unable to find where the effect took place. 

Thanks for all your help!

**Comment by ebaauw** [comment]
The effect is the verbosity of messages in the Homebridge log, see https://github.com/ebaauw/homebridge-lib/wiki/Log-Messages.

**Comment by PNWOregon** [comment]
Thank you for your help and the information!
