### ISSUE TITLE
noLeak: Invalid key

### ISSUE THREAD

**Issue by Pblondin123** [ebaauw/homebridge-ws#55]
Hello i saw this in the log not sure if it's parameter based thanks:  [Weather] warning: config.json: noLeak: invalid key

**Comment by ebaauw** [comment]
That config.json key has been removed since [v2.7.0](https://github.com/ebaauw/homebridge-ws/releases/tag/v2.7.0).

**Comment by Pblondin123** [comment]
ok am at v2.7.25 so is there anything specific to be done to cleanup on my part ?  thanks

**Comment by ebaauw** [comment]
Just remove it from config.json.
